return Def.ActorFrame{
	Def.ActorFrame{
		InitCommand=cmd(player,PLAYER_1;x,-200;y,105;zoom,1);
		LoadActor("OK")..{
			OnCommand=cmd(zoomx,0);
			OffCommand=cmd(linear,0.1;zoomy,1;sleep,0.5;linear,0.1;zoomy,0);
			ExitSelectedP1Command=function(self)
				setenv("PlayerOptionExitP1",true);
				(cmd(stoptweening;bounceend,0.2;zoomx,1;))(self)
			end;
			ExitUnselectedP1Command=function(self)
				setenv("PlayerOptionExitP1",false);
				(cmd(stoptweening;zoomx,0;))(self)
			end;
		};
		LoadActor("WAIT")..{
			OnCommand=cmd(zoomy,0);
			OffCommand=cmd(zoomy,1);
		};
	};
	Def.ActorFrame{
		InitCommand=cmd(player,PLAYER_2;x,200;y,105;zoom,1);
		LoadActor("OK")..{
			OnCommand=cmd(zoomx,0);
			OffCommand=cmd(linear,0.1;zoomy,1;sleep,0.5;linear,0.1;zoomy,0);
			ExitSelectedP2Command=function(self)
				setenv("PlayerOptionExitP2",true);
				(cmd(stoptweening;bounceend,0.2;zoomx,1;))(self)
			end;
			ExitUnselectedP2Command=function(self)
				setenv("PlayerOptionExitP2",false);
				(cmd(stoptweening;zoomx,0;))(self)
			end;
		};
		LoadActor("WAIT")..{
			OnCommand=cmd(zoomy,0);
			OffCommand=cmd(zoomy,1);
		};
	};
};
